# -*- coding: utf-8 -*-
"""Hands_On_with_R.html.ipynb

Automatically generated by Colaboratory.


Original file is located at
    https://colab.research.google.com/drive/1ubmmPTYGPAc0Y85ejOdxA2MPNUC-yJtO

# **Hands On with R**
## Created by **Ramses Alexander Coraspe Valdez**
## Created on July 1, 2020

### **An object can be created with the operator <- or -> depending on the direction in which the object is assigned:**
"""

n <- 15
n
5 -> n
n
x <- 1
X <- 10
x
X

"""### **Every object has two intrinsic attributes: type and length**"""

x <- 1
mode(x)
length(x)
A <- "Ramses"; compar <- TRUE; z <- 1i
mode(A); mode(compar); mode(z)

"""### **Vectors**"""

# vectores, arrays
vector.1 <- c(1,10,100,1000) 
vector.1[4] #1-based index
vector.1 + 1 
vector.1 * 2
vector.2 <- c(8, 15)
vector.2

"""### **DataFrames**"""

x <- 1:4; n <- 10; M <- c(10, 35); y <- 2:4
data.frame(x, n)

data.frame(x, M)

"""### **Lists**"""

Lista1 <- list(x, y); Lista2 <- list(A=x, B=y)
Lista1
Lista2
names(Lista1)
names(Lista2)

"""### **Arrays**"""

# matrices
1:100
100:1
seq(1,100, 4)
?matrix
mtx.1 <- matrix(data=1:100, nrow=10, ncol=11)
mtx.1
